name: Test and Update on Push

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - dev
      - main

env:
  BRANCHNAME: ${{ github.GITHUB_REF_NAME }}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: install packages
        run: |
          npm install
      - name: run unit tests
        run: |
          npm run unittest
  integration-test:
    runs-on: ubuntu-latest
    needs: [unit-test]
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: install packages
        run: |
          echo "BRANCHNAME: ${{env.BRANCHNAME}}"
          npm install
      - name: run integration tests
        run: |
          npm run inttest
  update-stack:
    runs-on: ubuntu-latest
    needs: [unit-test, integration-test]
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: install packages
        run: |
            echo "BRANCHNAME: ${{env.BRANCHNAME}}"
            npm install
      - name: pulumi up the stack
        uses: pulumi/actions@v3
        with:
          command: update
          work-dir: ./src
          stack-name: ${{env.BRANCHNAME}}
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
