name: Update on Push

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - dev
      - main

jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "GITHUB_REF_NAME: $BRANCH_NAME"
          npm install
      - uses: pulumi/actions@v3
        with:
          command: update
          stack-name: $BRANCH_NAME
          upsert: true
        env:
          BRANCHNAME: ${{ github.GITHUB_REF_NAME }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
